apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterconnect-config
  namespace: default
data:
  PORT: "5000"
  NODE_ENV: "production"
  KAFKA_BROKER: "kafka-service:9092"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
